// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddOAuthProviderV1 implements Add_Oauth_Provider_V1 operation.
//
// Add oauth provider.
//
// POST /v1/oauth/add
func (UnimplementedHandler) AddOAuthProviderV1(ctx context.Context, req *AddOAuthProviderV1Req) (r *AddOAuthProviderV1Forbidden, _ error) {
	return r, ht.ErrNotImplemented
}

// DeviceAddV1 implements Device_Add_V1 operation.
//
// Add device.
//
// POST /v1/devices/add
func (UnimplementedHandler) DeviceAddV1(ctx context.Context, req *DeviceAddV1Req) (r *DeviceAddStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// Livenesprobe implements Livenesprobe operation.
//
// Livenes Probe.
//
// GET /livenes
func (UnimplementedHandler) Livenesprobe(ctx context.Context) (r *LivenesProbeStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginUserV1 implements Login_User_V1 operation.
//
// Login user.
//
// POST /v1/user/login
func (UnimplementedHandler) LoginUserV1(ctx context.Context, req *LoginUserV1Req) (r LoginUserV1Res, _ error) {
	return r, ht.ErrNotImplemented
}

// UserRegisterV1 implements User_Register_V1 operation.
//
// Register new user.
//
// POST /v1/user/register
func (UnimplementedHandler) UserRegisterV1(ctx context.Context, req *RegisterNewUser) (r UserRegisterV1Res, _ error) {
	return r, ht.ErrNotImplemented
}
