// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	AddOAuthProviderV1Operation OperationName = "AddOAuthProviderV1"
	DeviceAddV1Operation        OperationName = "DeviceAddV1"
	LivenesprobeOperation       OperationName = "Livenesprobe"
	LoginUserV1Operation        OperationName = "LoginUserV1"
	UserRegisterV1Operation     OperationName = "UserRegisterV1"
)
